baseURL = 'https://blog.zinuo.me/'
languageCode = 'en-us'
title = 'ZINUO ME'
theme = 'hugo-bearblog-neo'

[params]
    upvote = true
    upvoteURL = "post-upvote.zinuo-lee.workers.dev/" 
    postSearch = true
    groupByYear = true
    toc = true